<?php

namespace App\Services\Reports;

use App\Models\ActionItem;
use App\Models\ActionItemStatusHistory;
use App\Models\ClinicalAlertRule;
use App\Models\Report;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

/** Maintains durable, human-owned work generated by clinical alert rules. */
class ActionItemService
{
    /**
     * @param  list<array{rule: ClinicalAlertRule|null, fieldKey: string, label: string, total: float, threshold: float, triggered: bool, severity: string, deadlineHours: int, responsibleRole: string|null, notificationRoles: list<string>}>  $evaluations
     * @return list<array{type: string, item: ActionItem, evaluation: array<string, mixed>}>
     */
    public function recordEvaluations(Report $report, array $evaluations, Carbon $now): array
    {
        $events = [];
        $report->loadMissing('department');

        foreach ($evaluations as $evaluation) {
            $activeItem = ActionItem::query()
                ->where('source', 'critical_event')
                ->where('report_id', $report->id)
                ->where('field_key', $evaluation['fieldKey'])
                ->whereIn('status', ActionItem::OUTSTANDING_STATUSES)
                ->latest('created_at')
                ->first();

            if ($evaluation['triggered']) {
                if ($activeItem) {
                    $wasCorrected = $activeItem->condition_state === 'corrected_pending_review';
                    $activeItem->fill([
                        'clinical_alert_rule_id' => $evaluation['rule']?->id,
                        'rule_version' => $evaluation['rule']?->version,
                        'observed_value' => $evaluation['total'],
                        'trigger_threshold' => $evaluation['threshold'],
                        'trigger_operator' => $evaluation['rule']?->operator ?? 'gt',
                        'condition_state' => 'triggered',
                        'title' => $this->title($report, $evaluation['label']),
                        'description' => $this->description($report, $evaluation),
                        'severity' => $evaluation['severity'],
                        'responsible_role' => $evaluation['responsibleRole'],
                    ]);
                    $activeItem->due_at ??= $now->copy()->addHours($evaluation['deadlineHours']);
                    $activeItem->save();

                    if ($wasCorrected) {
                        $this->history($activeItem, 'condition_recurred', $activeItem->status, $activeItem->status, 'The critical condition appeared again after a data correction.', null, $now);
                        $events[] = ['type' => 'recurred', 'item' => $activeItem, 'evaluation' => $evaluation];
                    }

                    continue;
                }

                $item = ActionItem::query()->create([
                    'report_id' => $report->id,
                    'department_id' => $report->department_id,
                    'clinical_alert_rule_id' => $evaluation['rule']?->id,
                    'rule_version' => $evaluation['rule']?->version,
                    'source' => 'critical_event',
                    'source_key' => $this->sourceKey($report, $evaluation['fieldKey']),
                    'field_key' => $evaluation['fieldKey'],
                    'observed_value' => $evaluation['total'],
                    'trigger_threshold' => $evaluation['threshold'],
                    'trigger_operator' => $evaluation['rule']?->operator ?? 'gt',
                    'title' => $this->title($report, $evaluation['label']),
                    'description' => $this->description($report, $evaluation),
                    'severity' => $evaluation['severity'],
                    'status' => 'open',
                    'condition_state' => 'triggered',
                    'responsible_role' => $evaluation['responsibleRole'],
                    'due_at' => $now->copy()->addHours($evaluation['deadlineHours']),
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);

                $this->history($item, 'opened', null, 'open', 'Created automatically from a clinical alert rule.', null, $now);
                $events[] = ['type' => 'triggered', 'item' => $item, 'evaluation' => $evaluation];

                continue;
            }

            if ($activeItem && $activeItem->condition_state !== 'corrected_pending_review') {
                $activeItem->forceFill([
                    'observed_value' => $evaluation['total'],
                    'trigger_threshold' => $evaluation['threshold'],
                    'trigger_operator' => $evaluation['rule']?->operator ?? 'gt',
                    'rule_version' => $evaluation['rule']?->version,
                    'condition_state' => 'corrected_pending_review',
                    'updated_at' => $now,
                ])->save();
                $this->history($activeItem, 'data_corrected', $activeItem->status, $activeItem->status, 'The report value no longer meets the alert rule. Human verification is still required.', null, $now);
                $events[] = ['type' => 'corrected', 'item' => $activeItem, 'evaluation' => $evaluation];
            }
        }

        if ($events !== []) {
            Cache::forget(ActionItemDashboardService::CACHE_KEY);
        }

        return $events;
    }

    /** @param list<array{fieldKey: string, label: string, total: float}> $triggered */
    public function recordCriticalEvent(Report $report, array $triggered, Carbon $now): ?ActionItem
    {
        $events = $this->recordEvaluations($report, array_map(fn (array $item): array => [
            'rule' => null,
            'fieldKey' => $item['fieldKey'],
            'label' => $item['label'],
            'total' => $item['total'],
            'threshold' => 0.0,
            'triggered' => true,
            'severity' => 'high',
            'deadlineHours' => 24,
            'responsibleRole' => 'admin',
            'notificationRoles' => ['superadmin', 'admin'],
        ], $triggered), $now);

        return $events[0]['item'] ?? null;
    }

    public function history(ActionItem $item, string $event, ?string $fromStatus, ?string $toStatus, ?string $note, ?string $actorId, ?Carbon $at = null): ActionItemStatusHistory
    {
        return ActionItemStatusHistory::query()->create([
            'action_item_id' => $item->id,
            'event' => $event,
            'from_status' => $fromStatus,
            'to_status' => $toStatus,
            'note' => $note,
            'changed_by' => $actorId,
            'created_at' => $at ?? now(),
        ]);
    }

    /** @param array{total: float, threshold: float} $evaluation */
    private function description(Report $report, array $evaluation): string
    {
        return sprintf(
            '%s reported %s. The configured rule is %s %s. Investigate, document the follow-up, and verify closure.',
            $report->department?->name ?? 'A department',
            $this->formatTotal($evaluation['total']),
            match ($evaluation['rule']?->operator ?? 'gt') {
                'gte' => 'at least',
                'eq' => 'exactly',
                default => 'greater than',
            },
            $this->formatTotal($evaluation['threshold']),
        );
    }

    private function title(Report $report, string $label): string
    {
        return sprintf('%s in %s', $label, $report->department?->name ?? 'a department');
    }

    private function sourceKey(Report $report, string $fieldKey): string
    {
        $hasAny = ActionItem::query()->where('source', 'critical_event')->where('report_id', $report->id)->exists();

        return $hasAny ? sprintf('%s:%s:%s', $report->id, $fieldKey, Str::uuid()) : $report->id;
    }

    private function formatTotal(float $total): string
    {
        return floor($total) === $total ? (string) (int) $total : (string) $total;
    }
}
