<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Generated by RotationCalendarService, never entered by hand.
        Schema::create('rotation_blocks', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('calendar_id')->constrained('rotation_calendars')->cascadeOnDelete();
            $table->unsignedTinyInteger('block_index');
            $table->date('starts_on');
            $table->date('ends_on');
            $table->timestamps();

            $table->unique(['calendar_id', 'block_index']);
            $table->index(['starts_on', 'ends_on']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('rotation_blocks');
    }
};
